In [1]:
import numpy as np
import pandas as pd
import datetime
# from datetime import datetime

In [2]:
df = pd.read_excel('000002.xlsx')
df

ユーザーID  モデルID         モデル名  カメラID  カメラ名  カメラエリアID  クラスID     クラス名  \
0          2      1  Bobbin_v1.0      2  22号機         6      0       稼働   
1          2      1  Bobbin_v1.0      2  22号機         6      0       稼働   
2          2      1  Bobbin_v1.0      2  22号機         7      0       稼働   
3          2      1  Bobbin_v1.0      2  22号機         9      0       稼働   
4          2      1  Bobbin_v1.0      2  22号機        10      0       稼働   
...      ...    ...          ...    ...   ...       ...    ...      ...   
8588       2      1  Bobbin_v1.0      2  22号機        38    999  NO_DATA   
8589       2      1  Bobbin_v1.0      2  22号機        39    999  NO_DATA   
8590       2      1  Bobbin_v1.0      2  22号機        40    999  NO_DATA   
8591       2      1  Bobbin_v1.0      2  22号機        41    999  NO_DATA   
8592       2      1  Bobbin_v1.0      2  22号機         6    999  NO_DATA   

      精度スコア  作業者名  指示書名                 検出日時  経過時間  
0      0.00     1     0  2022-12-01 23:59:59     0  
1      0.96     1     0  2022-12-01 23:59:32    27  
2      0.84     1     0  2022-12-01 23:59:32     0  
3      0.82     1     0  2022-12-01 23:59:32     0  
4      0.05     1     0  2022-12-01 23:59:32     0  
...     ...   ...   ...                  ...   ...  
8588   1.00     1     0  2022-12-01 00:00:46     0  
8589   1.00     1     0  2022-12-01 00:00:46     0  
8590   1.00     1     0  2022-12-01 00:00:46     0  
8591   1.00     1     0  2022-12-01 00:00:46     0  
8592   0.00     1     0  2022-12-01 00:00:00    46  

[8593 rows x 13 columns]

In [3]:
df.drop(['ユーザーID', 'モデルID', 'モデル名', 'カメラID', 'カメラ名', '作業者名', '指示書名'], axis = 1, inplace=True)

In [4]:
df.head(2)

カメラエリアID  クラスID クラス名  精度スコア                 検出日時  経過時間
0         6      0   稼働   0.00  2022-12-01 23:59:59     0
1         6      0   稼働   0.96  2022-12-01 23:59:32    27

In [5]:
df.shape

(8593, 6)

In [6]:
df['経過時間'].unique()

array([  0,  27,  15, 266, 270, 268, 271, 267, 254, 272, 177,  14,  43,
        41, 276,  16, 148,  17,  57, 120, 217, 190, 273,  95, 194,  13,
        70,  58, 212, 280,  74, 263,  56, 277, 274,  72, 206, 281,  46,
       285, 103, 286, 284, 282, 283, 113, 169,  62,  22, 279, 275, 255,
         1, 251, 126, 278, 235, 308,  59,   9,  84,  99, 290, 257, 323,
       289, 295, 328, 331, 300, 310, 292, 291, 259, 264, 204, 939,  25,
       354, 355, 372, 337, 325, 305, 314, 298, 344,  34, 200, 287,  18,
        35,  32,  31,  29,  42,  30,  44,  28, 155, 100, 136, 208,  73,
       299, 433, 413, 461, 369, 335,  47,  76, 306, 205, 256,  55, 320,
       288, 311, 348, 332, 327, 330, 378, 230,  63, 296, 302, 293,   6,
       301, 172, 107, 303, 297, 156, 294, 199, 127, 150], dtype=int64)

In [7]:
df['カメラエリアID'].value_counts()   # " カメラエリアID "  ==  " Camera Area ID "  

#  Only for " カメラエリアID " == 6, value is 433 for rest it is only 408

6     433
32    408
29    408
31    408
15    408
7     408
38    408
30    408
14    408
37    408
13    408
40    408
36    408
12    408
35    408
34    408
10    408
41    408
33    408
9     408
39    408
Name: カメラエリアID, dtype: int64

In [8]:
df['カメラエリアID'].unique()

array([ 6,  7,  9, 10, 12, 13, 14, 15, 29, 30, 31, 32, 33, 34, 35, 36, 37,
       38, 39, 40, 41], dtype=int64)

In [9]:
grp = df.groupby('カメラエリアID')

In [10]:
# group for eaach " Camera Area ID "

grp.first()

クラスID     クラス名  精度スコア                 検出日時  経過時間
カメラエリアID                                                  
6             0       稼働   0.00  2022-12-01 23:59:59     0
7             0       稼働   0.84  2022-12-01 23:59:32     0
9             0       稼働   0.82  2022-12-01 23:59:32     0
10            0       稼働   0.05  2022-12-01 23:59:32     0
12            0       稼働   0.26  2022-12-01 23:59:32     0
13            0       稼働   0.95  2022-12-01 23:59:32     0
14            0       稼働   0.95  2022-12-01 23:59:32     0
15          999  NO_DATA   1.00  2022-12-01 23:59:32     0
29            0       稼働   0.95  2022-12-01 23:59:32     0
30            0       稼働   0.88  2022-12-01 23:59:32     0
31            0       稼働   0.82  2022-12-01 23:59:32     0
32            0       稼働   0.93  2022-12-01 23:59:32     0
33            0       稼働   0.94  2022-12-01 23:59:32     0
34            0       稼働   0.94  2022-12-01 23:59:32     0
35            0       稼働   0.94  2022-12-01 23:59:32     0
36            0       稼働   0.91  2022-12-01 23:59:32     0
37            0       稼働   0.91  2022-12-01 23:59:32     0
38            0       稼働   0.94  2022-12-01 23:59:32     0
39            0       稼働   0.94  2022-12-01 23:59:32     0
40            0       稼働   0.93  2022-12-01 23:59:32     0
41            0       稼働   0.93  2022-12-01 23:59:32     0

In [11]:
# Elapsed Time for " Camera Area ID " == 6 and different " detection date and time " 

grp.get_group(6) #  " クラス名 " == " Class Name "

## Accuracy Score  == " 2022-12-01 23:59:59  -  2022-12-01 23:59:32 / 100 "

カメラエリアID  クラスID     クラス名  精度スコア                 検出日時  経過時間
0            6      0       稼働   0.00  2022-12-01 23:59:59     0
1            6      0       稼働   0.96  2022-12-01 23:59:32    27
22           6      0       稼働   0.86  2022-12-01 23:59:17    15
43           6      0       稼働   0.90  2022-12-01 23:59:02    15
64           6      0       稼働   0.93  2022-12-01 23:54:36   266
...        ...    ...      ...    ...                  ...   ...
8508         6    999  NO_DATA   1.00  2022-12-01 00:14:53   287
8529         6    999  NO_DATA   1.00  2022-12-01 00:10:13   280
8550         6    999  NO_DATA   1.00  2022-12-01 00:05:30   283
8571         6    999  NO_DATA   1.00  2022-12-01 00:00:46   284
8592         6    999  NO_DATA   0.00  2022-12-01 00:00:00    46

[433 rows x 6 columns]

In [12]:
# size() acts same as value_counts()

grp.size()

カメラエリアID
6     433
7     408
9     408
10    408
12    408
13    408
14    408
15    408
29    408
30    408
31    408
32    408
33    408
34    408
35    408
36    408
37    408
38    408
39    408
40    408
41    408
dtype: int64

In [13]:
# Different Elapsed Time for " Camera Area ID " == 6

grp.get_group(6)['経過時間'].unique()

array([  0,  27,  15, 266, 270, 268, 271, 267, 254, 272, 177,  14,  43,
        41, 276,  16, 148,  17,  57, 120, 217, 190, 273,  95, 194,  13,
        70,  58, 212, 280,  74, 263,  56, 277, 274,  72, 206, 281,  46,
       285, 103, 286, 284, 282, 283, 113, 169,  62,  22, 279, 275, 255,
         1, 251, 126, 278, 235, 308,  59,   9,  84,  99, 290, 257, 323,
       289, 295, 328, 331, 300, 310, 292, 291, 259, 264, 204, 939,  25,
       354, 355, 372, 337, 325, 305, 314, 298, 344,  34, 200, 287,  18,
        35,  32,  31,  29,  42,  30,  44,  28, 155, 100, 136, 208,  73,
       299, 433, 413, 461, 369, 335,  47,  76, 306, 205, 256,  55, 320,
       288, 311, 348, 332, 327, 330, 378, 230,  63, 296, 302, 293,   6,
       301, 172, 107, 303, 297, 156, 294, 199, 127, 150], dtype=int64)

In [14]:
grp.get_group(7)['経過時間'].unique()  ##  Only one Elapsed Time for " Camera Area ID " == 7

array([0], dtype=int64)

In [15]:


# grp2 = df.groupby(['カメラエリアID', '検出日時'])
# # 46 is Elapsed time for " Camera Area ID " == 6 and " Time detection date " ==  " 2022-12-01 00:00:00 "

# grp2.last()
# grp2.get_group((6, '2022-12-01 00:00:00'))['経過時間'].unique()
# grp2.get_group((41, '2022-12-01 23:54:36'))['経過時間'].unique()



In [16]:
df.dtypes  ##  Here we can see that the " Elapsed Time " is is Integer, should convert it to " datetime "

カメラエリアID      int64
クラスID         int64
クラス名         object
精度スコア       float64
検出日時         object
経過時間          int64
dtype: object

In [17]:
# df['経過時間_New'] = pd.to_datetime(df['経過時間'], format='%m/%d/%Y %H:%M:%S.%f',infer_datetime_format=True) 
# format='%Y:%m:%d:%H:%M:%S') #%m/%d/%Y %H:%M:%S.%f 

In [18]:
df['経過時間_New'] = pd.to_timedelta(df['経過時間'], unit='s')
df['経過時間_New']

0      0 days 00:00:00
1      0 days 00:00:27
2      0 days 00:00:00
3      0 days 00:00:00
4      0 days 00:00:00
             ...      
8588   0 days 00:00:00
8589   0 days 00:00:00
8590   0 days 00:00:00
8591   0 days 00:00:00
8592   0 days 00:00:46
Name: 経過時間_New, Length: 8593, dtype: timedelta64[ns]

In [19]:
df.dtypes

カメラエリアID              int64
クラスID                 int64
クラス名                 object
精度スコア               float64
検出日時                 object
経過時間                  int64
経過時間_New    timedelta64[ns]
dtype: object

In [20]:
df[df['カメラエリアID'] == 6]

カメラエリアID  クラスID     クラス名  精度スコア                 検出日時  経過時間  \
0            6      0       稼働   0.00  2022-12-01 23:59:59     0   
1            6      0       稼働   0.96  2022-12-01 23:59:32    27   
22           6      0       稼働   0.86  2022-12-01 23:59:17    15   
43           6      0       稼働   0.90  2022-12-01 23:59:02    15   
64           6      0       稼働   0.93  2022-12-01 23:54:36   266   
...        ...    ...      ...    ...                  ...   ...   
8508         6    999  NO_DATA   1.00  2022-12-01 00:14:53   287   
8529         6    999  NO_DATA   1.00  2022-12-01 00:10:13   280   
8550         6    999  NO_DATA   1.00  2022-12-01 00:05:30   283   
8571         6    999  NO_DATA   1.00  2022-12-01 00:00:46   284   
8592         6    999  NO_DATA   0.00  2022-12-01 00:00:00    46   

            経過時間_New  
0    0 days 00:00:00  
1    0 days 00:00:27  
22   0 days 00:00:15  
43   0 days 00:00:15  
64   0 days 00:04:26  
...              ...  
8508 0 days 00:04:47  
8529 0 days 00:04:40  
8550 0 days 00:04:43  
8571 0 days 00:04:44  
8592 0 days 00:00:46  

[433 rows x 7 columns]

In [21]:
# # Elapsed time for status data
# grp3 = df[["カメラエリアID","クラス名","経過時間_New"]].groupby(["カメラエリアID","クラス名"]).sum()
# grp3 = grp3.reset_index()
# # status_data2
# group_data = grp3[['クラス名','経過時間_New']]
# group_data

In [22]:
# # Elapsed time for status data
# grp4 = df[["カメラエリアID",'クラス名',"経過時間_New"]].groupby(["カメラエリアID","クラス名"]).sum()
# grp4 = grp4.reset_index()
# # status_data2
# group_data2 = grp4[['カメラエリアID','経過時間_New']]
# group_data2[group_data2['カメラエリアID'] == 6]

In [23]:
# Elapsed time for status data
grp5 = df[["カメラエリアID","クラス名","経過時間_New"]].groupby(["カメラエリアID", "経過時間_New"]).sum().reset_index()
print(type(grp5))
#  grp2 = df.groupby(['カメラエリアID', '検出日時'])

# status_data2
group_data3 = grp5[['カメラエリアID','経過時間_New']]
group_data3[group_data3['カメラエリアID'] == 6]

<class 'pandas.core.frame.DataFrame'>


カメラエリアID        経過時間_New
0           6 0 days 00:00:00
1           6 0 days 00:00:01
2           6 0 days 00:00:06
3           6 0 days 00:00:09
4           6 0 days 00:00:13
..        ...             ...
135         6 0 days 00:06:18
136         6 0 days 00:06:53
137         6 0 days 00:07:13
138         6 0 days 00:07:41
139         6 0 days 00:15:39

[140 rows x 2 columns]

In [24]:
x = grp5[grp5['クラス名'] == "NO_DATA"]['経過時間_New']    #- grp5[grp5['クラス名'] == "稼働"]['経過時間_New'] 

In [25]:
y = grp5[grp5['クラス名'] == "稼働"]['経過時間_New']

In [26]:
grp5['Sub'] = x - y

In [27]:
grp5.head(2)

カメラエリアID        経過時間_New  クラス名 Sub
0         6 0 days 00:00:00    稼働 NaT
1         6 0 days 00:00:01  稼働稼働 NaT

In [28]:
# groupby and calc the diff between the groups from the first timestamp when sorted
# grp5['diff'] = grp5.groupby(['経過時間_New', 'クラス名'])['経過時間_New'].apply(lambda x: x - x.iloc[0])

# filter dataframe where the diff is less than 1 hour and does not equal 0
# dup[(dup['diff'] < pd.Timedelta('1 hour')) & (dup['diff'] != pd.Timedelta('0 hour'))]

In [29]:
# grp5['Time_Diff'] = pd.to_datetime(x) - pd.to_datetime(y)

In [30]:
grp5.dtypes

カメラエリアID              int64
経過時間_New    timedelta64[ns]
クラス名                 object
Sub         timedelta64[ns]
dtype: object

In [31]:
grp5

カメラエリアID        経過時間_New  \
0           6 0 days 00:00:00   
1           6 0 days 00:00:01   
2           6 0 days 00:00:06   
3           6 0 days 00:00:09   
4           6 0 days 00:00:13   
..        ...             ...   
155        37 0 days 00:00:00   
156        38 0 days 00:00:00   
157        39 0 days 00:00:00   
158        40 0 days 00:00:00   
159        41 0 days 00:00:00   

                                                  クラス名 Sub  
0                                                   稼働 NaT  
1                                                 稼働稼働 NaT  
2                                              NO_DATA NaT  
3                                                 稼働稼働 NaT  
4                                                 稼働稼働 NaT  
..                                                 ...  ..  
155  稼働稼働稼働稼働稼働稼働稼働稼働稼働稼働稼働稼働稼働稼働NO_DATA稼働稼働稼働稼働稼働稼... NaT  
156  稼働稼働稼働稼働稼働稼働稼働稼働稼働稼働稼働稼働稼働稼働稼働稼働稼働稼働稼働稼働稼働稼働NO... NaT  
157  稼働稼働稼働稼働稼働稼働稼働稼働NO_DATANO_DATA稼働NO_DATA稼働稼働NO_... NaT  
158  稼働稼働稼働稼働稼働稼働稼働稼働稼働稼働稼働稼働稼働稼働稼働NO_DATANO_DATA稼働... NaT  
159  稼働稼働稼働稼働稼働稼働稼働稼働稼働稼働稼働稼働稼働稼働稼働稼働稼働稼働稼働稼働稼働稼働稼働... NaT  

[160 rows x 4 columns]