In [1]:
import numpy as np
import pandas as pd
import datetime
# from datetime import datetime

In [2]:
df = pd.read_excel('000002.xlsx')
df

ユーザーID  モデルID         モデル名  カメラID  カメラ名  カメラエリアID  クラスID     クラス名  \
0          2      1  Bobbin_v1.0      2  22号機         6      0       稼働   
1          2      1  Bobbin_v1.0      2  22号機         6      0       稼働   
2          2      1  Bobbin_v1.0      2  22号機         7      0       稼働   
3          2      1  Bobbin_v1.0      2  22号機         9      0       稼働   
4          2      1  Bobbin_v1.0      2  22号機        10      0       稼働   
...      ...    ...          ...    ...   ...       ...    ...      ...   
8588       2      1  Bobbin_v1.0      2  22号機        38    999  NO_DATA   
8589       2      1  Bobbin_v1.0      2  22号機        39    999  NO_DATA   
8590       2      1  Bobbin_v1.0      2  22号機        40    999  NO_DATA   
8591       2      1  Bobbin_v1.0      2  22号機        41    999  NO_DATA   
8592       2      1  Bobbin_v1.0      2  22号機         6    999  NO_DATA   

      精度スコア  作業者名  指示書名                 検出日時  経過時間  
0      0.00     1     0  2022-12-01 23:59:59     0  
1      0.96     1     0  2022-12-01 23:59:32    27  
2      0.84     1     0  2022-12-01 23:59:32     0  
3      0.82     1     0  2022-12-01 23:59:32     0  
4      0.05     1     0  2022-12-01 23:59:32     0  
...     ...   ...   ...                  ...   ...  
8588   1.00     1     0  2022-12-01 00:00:46     0  
8589   1.00     1     0  2022-12-01 00:00:46     0  
8590   1.00     1     0  2022-12-01 00:00:46     0  
8591   1.00     1     0  2022-12-01 00:00:46     0  
8592   0.00     1     0  2022-12-01 00:00:00    46  

[8593 rows x 13 columns]

In [19]:
df['経過時間'].unique()

array([  0,  27,  15, 266, 270, 268, 271, 267, 254, 272, 177,  14,  43,
        41, 276,  16, 148,  17,  57, 120, 217, 190, 273,  95, 194,  13,
        70,  58, 212, 280,  74, 263,  56, 277, 274,  72, 206, 281,  46,
       285, 103, 286, 284, 282, 283, 113, 169,  62,  22, 279, 275, 255,
         1, 251, 126, 278, 235, 308,  59,   9,  84,  99, 290, 257, 323,
       289, 295, 328, 331, 300, 310, 292, 291, 259, 264, 204, 939,  25,
       354, 355, 372, 337, 325, 305, 314, 298, 344,  34, 200, 287,  18,
        35,  32,  31,  29,  42,  30,  44,  28, 155, 100, 136, 208,  73,
       299, 433, 413, 461, 369, 335,  47,  76, 306, 205, 256,  55, 320,
       288, 311, 348, 332, 327, 330, 378, 230,  63, 296, 302, 293,   6,
       301, 172, 107, 303, 297, 156, 294, 199, 127, 150], dtype=int64)

In [3]:
df.shape

(8593, 13)

In [4]:
df['カメラエリアID'].value_counts()   # " カメラエリアID "  ==  " Camera Area ID "  

#  Only for " カメラエリアID " == 6, value is 433 for rest it is only 408

6     433
32    408
29    408
31    408
15    408
7     408
38    408
30    408
14    408
37    408
13    408
40    408
36    408
12    408
35    408
34    408
10    408
41    408
33    408
9     408
39    408
Name: カメラエリアID, dtype: int64

In [5]:
grp = df.groupby('カメラエリアID')

In [6]:
# group for eaach " Camera Area ID "

grp.first()

ユーザーID  モデルID         モデル名  カメラID  カメラ名  クラスID     クラス名  精度スコア  \
カメラエリアID                                                                   
6              2      1  Bobbin_v1.0      2  22号機      0       稼働   0.00   
7              2      1  Bobbin_v1.0      2  22号機      0       稼働   0.84   
9              2      1  Bobbin_v1.0      2  22号機      0       稼働   0.82   
10             2      1  Bobbin_v1.0      2  22号機      0       稼働   0.05   
12             2      1  Bobbin_v1.0      2  22号機      0       稼働   0.26   
13             2      1  Bobbin_v1.0      2  22号機      0       稼働   0.95   
14             2      1  Bobbin_v1.0      2  22号機      0       稼働   0.95   
15             2      1  Bobbin_v1.0      2  22号機    999  NO_DATA   1.00   
29             2      1  Bobbin_v1.0      2  22号機      0       稼働   0.95   
30             2      1  Bobbin_v1.0      2  22号機      0       稼働   0.88   
31             2      1  Bobbin_v1.0      2  22号機      0       稼働   0.82   
32             2      1  Bobbin_v1.0      2  22号機      0       稼働   0.93   
33             2      1  Bobbin_v1.0      2  22号機      0       稼働   0.94   
34             2      1  Bobbin_v1.0      2  22号機      0       稼働   0.94   
35             2      1  Bobbin_v1.0      2  22号機      0       稼働   0.94   
36             2      1  Bobbin_v1.0      2  22号機      0       稼働   0.91   
37             2      1  Bobbin_v1.0      2  22号機      0       稼働   0.91   
38             2      1  Bobbin_v1.0      2  22号機      0       稼働   0.94   
39             2      1  Bobbin_v1.0      2  22号機      0       稼働   0.94   
40             2      1  Bobbin_v1.0      2  22号機      0       稼働   0.93   
41             2      1  Bobbin_v1.0      2  22号機      0       稼働   0.93   

          作業者名  指示書名                 検出日時  経過時間  
カメラエリアID                                         
6            1     0  2022-12-01 23:59:59     0  
7            1     0  2022-12-01 23:59:32     0  
9            1     0  2022-12-01 23:59:32     0  
10           1     0  2022-12-01 23:59:32     0  
12           1     0  2022-12-01 23:59:32     0  
13           1     0  2022-12-01 23:59:32     0  
14           1     0  2022-12-01 23:59:32     0  
15           1     0  2022-12-01 23:59:32     0  
29           1     0  2022-12-01 23:59:32     0  
30           1     0  2022-12-01 23:59:32     0  
31           1     0  2022-12-01 23:59:32     0  
32           1     0  2022-12-01 23:59:32     0  
33           1     0  2022-12-01 23:59:32     0  
34           1     0  2022-12-01 23:59:32     0  
35           1     0  2022-12-01 23:59:32     0  
36           1     0  2022-12-01 23:59:32     0  
37           1     0  2022-12-01 23:59:32     0  
38           1     0  2022-12-01 23:59:32     0  
39           1     0  2022-12-01 23:59:32     0  
40           1     0  2022-12-01 23:59:32     0  
41           1     0  2022-12-01 23:59:32     0

In [7]:
# Elapsed Time for " Camera Area ID " == 6 and different " detection date and time " 

grp.get_group(6) #  " クラス名 " == " Class Name "

## Accuracy Score  == " 2022-12-01 23:59:59  -  2022-12-01 23:59:32 / 100 "

ユーザーID  モデルID         モデル名  カメラID  カメラ名  カメラエリアID  クラスID     クラス名  \
0          2      1  Bobbin_v1.0      2  22号機         6      0       稼働   
1          2      1  Bobbin_v1.0      2  22号機         6      0       稼働   
22         2      1  Bobbin_v1.0      2  22号機         6      0       稼働   
43         2      1  Bobbin_v1.0      2  22号機         6      0       稼働   
64         2      1  Bobbin_v1.0      2  22号機         6      0       稼働   
...      ...    ...          ...    ...   ...       ...    ...      ...   
8508       2      1  Bobbin_v1.0      2  22号機         6    999  NO_DATA   
8529       2      1  Bobbin_v1.0      2  22号機         6    999  NO_DATA   
8550       2      1  Bobbin_v1.0      2  22号機         6    999  NO_DATA   
8571       2      1  Bobbin_v1.0      2  22号機         6    999  NO_DATA   
8592       2      1  Bobbin_v1.0      2  22号機         6    999  NO_DATA   

      精度スコア  作業者名  指示書名                 検出日時  経過時間  
0      0.00     1     0  2022-12-01 23:59:59     0  
1      0.96     1     0  2022-12-01 23:59:32    27  
22     0.86     1     0  2022-12-01 23:59:17    15  
43     0.90     1     0  2022-12-01 23:59:02    15  
64     0.93     1     0  2022-12-01 23:54:36   266  
...     ...   ...   ...                  ...   ...  
8508   1.00     1     0  2022-12-01 00:14:53   287  
8529   1.00     1     0  2022-12-01 00:10:13   280  
8550   1.00     1     0  2022-12-01 00:05:30   283  
8571   1.00     1     0  2022-12-01 00:00:46   284  
8592   0.00     1     0  2022-12-01 00:00:00    46  

[433 rows x 13 columns]

In [20]:
# size() acts same as value_counts()

grp.size()

カメラエリアID
6     433
7     408
9     408
10    408
12    408
13    408
14    408
15    408
29    408
30    408
31    408
32    408
33    408
34    408
35    408
36    408
37    408
38    408
39    408
40    408
41    408
dtype: int64

In [8]:
# Different Elapsed Time for " Camera Area ID " == 6

grp.get_group(6)['経過時間'].unique()

array([  0,  27,  15, 266, 270, 268, 271, 267, 254, 272, 177,  14,  43,
        41, 276,  16, 148,  17,  57, 120, 217, 190, 273,  95, 194,  13,
        70,  58, 212, 280,  74, 263,  56, 277, 274,  72, 206, 281,  46,
       285, 103, 286, 284, 282, 283, 113, 169,  62,  22, 279, 275, 255,
         1, 251, 126, 278, 235, 308,  59,   9,  84,  99, 290, 257, 323,
       289, 295, 328, 331, 300, 310, 292, 291, 259, 264, 204, 939,  25,
       354, 355, 372, 337, 325, 305, 314, 298, 344,  34, 200, 287,  18,
        35,  32,  31,  29,  42,  30,  44,  28, 155, 100, 136, 208,  73,
       299, 433, 413, 461, 369, 335,  47,  76, 306, 205, 256,  55, 320,
       288, 311, 348, 332, 327, 330, 378, 230,  63, 296, 302, 293,   6,
       301, 172, 107, 303, 297, 156, 294, 199, 127, 150], dtype=int64)

In [9]:
grp.get_group(7)['経過時間'].unique()  ##  Only one Elapsed Time for " Camera Area ID " == 7

array([0], dtype=int64)

In [10]:
grp2 = df.groupby(['カメラエリアID', '検出日時'])

In [11]:
# 46 is Elapsed time for " Camera Area ID " == 6 and " Time detection date " ==  " 2022-12-01 00:00:00 "

grp2.last()

ユーザーID  モデルID         モデル名  カメラID  カメラ名  クラスID  \
カメラエリアID 検出日時                                                                  
6        2022-12-01 00:00:00       2      1  Bobbin_v1.0      2  22号機    999   
         2022-12-01 00:00:46       2      1  Bobbin_v1.0      2  22号機    999   
         2022-12-01 00:05:30       2      1  Bobbin_v1.0      2  22号機    999   
         2022-12-01 00:10:13       2      1  Bobbin_v1.0      2  22号機    999   
         2022-12-01 00:14:53       2      1  Bobbin_v1.0      2  22号機    999   
...                              ...    ...          ...    ...   ...    ...   
41       2022-12-01 23:50:06       2      1  Bobbin_v1.0      2  22号機      0   
         2022-12-01 23:54:36       2      1  Bobbin_v1.0      2  22号機      0   
         2022-12-01 23:59:02       2      1  Bobbin_v1.0      2  22号機      0   
         2022-12-01 23:59:17       2      1  Bobbin_v1.0      2  22号機      0   
         2022-12-01 23:59:32       2      1  Bobbin_v1.0      2  22号機      0   

                                 クラス名  精度スコア  作業者名  指示書名  経過時間  
カメラエリアID 検出日時                                                   
6        2022-12-01 00:00:00  NO_DATA   0.00     1     0    46  
         2022-12-01 00:00:46  NO_DATA   1.00     1     0   284  
         2022-12-01 00:05:30  NO_DATA   1.00     1     0   283  
         2022-12-01 00:10:13  NO_DATA   1.00     1     0   280  
         2022-12-01 00:14:53  NO_DATA   1.00     1     0   287  
...                               ...    ...   ...   ...   ...  
41       2022-12-01 23:50:06       稼働   0.90     1     0     0  
         2022-12-01 23:54:36       稼働   0.90     1     0     0  
         2022-12-01 23:59:02       稼働   0.53     1     0     0  
         2022-12-01 23:59:17       稼働   0.67     1     0     0  
         2022-12-01 23:59:32       稼働   0.93     1     0     0  

[8593 rows x 11 columns]

In [12]:
grp2.get_group((6, '2022-12-01 00:00:00'))['経過時間'].unique()

array([46], dtype=int64)

In [13]:
grp2.get_group((41, '2022-12-01 23:54:36'))['経過時間'].unique()

array([0], dtype=int64)

In [64]:
df.dtypes  ##  Here we can see that the " Elapsed Time " is is Integer, should convert it to " datetime "

ユーザーID                 int64
モデルID                  int64
モデル名                  object
カメラID                  int64
カメラ名                  object
カメラエリアID               int64
クラスID                  int64
クラス名                  object
精度スコア                float64
作業者名                   int64
指示書名                   int64
検出日時                  object
経過時間                   int64
経過時間_New2    timedelta64[ns]
dtype: object

In [15]:
# df['経過時間_New'] = pd.to_datetime(df['経過時間'], format='%m/%d/%Y %H:%M:%S.%f',infer_datetime_format=True) 
# format='%Y:%m:%d:%H:%M:%S') #%m/%d/%Y %H:%M:%S.%f 

In [16]:
df['経過時間_New2'] = pd.to_timedelta(df['経過時間'], unit='s')
df['経過時間_New2']

0      0 days 00:00:00
1      0 days 00:00:27
2      0 days 00:00:00
3      0 days 00:00:00
4      0 days 00:00:00
             ...      
8588   0 days 00:00:00
8589   0 days 00:00:00
8590   0 days 00:00:00
8591   0 days 00:00:00
8592   0 days 00:00:46
Name: 経過時間_New2, Length: 8593, dtype: timedelta64[ns]

In [17]:
grp3 = df.groupby(['カメラエリアID', '経過時間'])

In [18]:
grp3.first()

ユーザーID  モデルID         モデル名  カメラID  カメラ名  クラスID     クラス名  精度スコア  \
カメラエリアID 経過時間                                                                   
6        0          2      1  Bobbin_v1.0      2  22号機      0       稼働   0.00   
         1          2      1  Bobbin_v1.0      2  22号機      0       稼働   0.95   
         6          2      1  Bobbin_v1.0      2  22号機    999  NO_DATA   1.00   
         9          2      1  Bobbin_v1.0      2  22号機      0       稼働   0.96   
         13         2      1  Bobbin_v1.0      2  22号機      0       稼働   0.92   
...               ...    ...          ...    ...   ...    ...      ...    ...   
37       0          2      1  Bobbin_v1.0      2  22号機      0       稼働   0.91   
38       0          2      1  Bobbin_v1.0      2  22号機      0       稼働   0.94   
39       0          2      1  Bobbin_v1.0      2  22号機      0       稼働   0.94   
40       0          2      1  Bobbin_v1.0      2  22号機      0       稼働   0.93   
41       0          2      1  Bobbin_v1.0      2  22号機      0       稼働   0.93   

               作業者名  指示書名                 検出日時       経過時間_New2  
カメラエリアID 経過時間                                                   
6        0        1     0  2022-12-01 23:59:59 0 days 00:00:00  
         1        1     0  2022-12-01 17:59:59 0 days 00:00:01  
         6        1     0  2022-12-01 07:59:54 0 days 00:00:06  
         9        1     0  2022-12-01 16:59:51 0 days 00:00:09  
         13       1     0  2022-12-01 22:40:37 0 days 00:00:13  
...             ...   ...                  ...             ...  
37       0        1     0  2022-12-01 23:59:32 0 days 00:00:00  
38       0        1     0  2022-12-01 23:59:32 0 days 00:00:00  
39       0        1     0  2022-12-01 23:59:32 0 days 00:00:00  
40       0        1     0  2022-12-01 23:59:32 0 days 00:00:00  
41       0        1     0  2022-12-01 23:59:32 0 days 00:00:00  

[160 rows x 12 columns]

In [59]:
El6 = df[df['カメラエリアID'] == 6]

In [61]:
El6

pandas.core.frame.DataFrame

In [51]:
##  To find the average " Elapsed Time " of each " Camera Area ID " 

def elapse_6(occurance):
    count = sum([1 for occ in occurance if occ == 6])
    return round(count / sum(occurance))



#     if df['カメラエリアID'] == 6:
#         return sum(df['経過時間']) / grp.size()
#     else:
#         return None

In [63]:
df['経過時間_AVG'] = df['経過時間'].apply(lambda x: elapse_6(x))

TypeError: 'int' object is not iterable

In [56]:
sum(df['経過時間']) # Elapsed 

86399

In [57]:
sum(df['カメラエリアID']) # Camera Area ID

220878